[package]
name = "bml"
version = "0.1.0"
authors = ["Rouven Spreckels <n3vu0r@qu1x.org>"]
edition = "2018"
description = "BML Markup Language"
documentation = "https://docs.rs/bml"
homepage = "https://qu1x.org/bml"
repository = "https://github.com/qu1x/bml"
readme = "README.md"
keywords = [
	"bml",
	"markup-language",
	"icarus-database",
	"higan-manifest",
	"bsnes-manifest",
]
categories = [
	"command-line-utilities",
	"parser-implementations",
	"encoding",
	"config",
]
license = "Fair"
include = [
	"src/lib.rs",
	"src/bml.pest",
	"Cargo.toml",
	"README.md",
	"RELEASES.md",
]

[badges]
travis-ci = { repository = "qu1x/bml" }

[dependencies]
err-derive = "0.1"
pest = "2"
pest_derive = "2"
smallstr = "0.1"
ordered-multimap = { version = "0.2", optional = true }
